### ISSUE TITLE
SEO Basics - Module 1 

### ISSUE THREAD

**Issue by NaSabbir** [XpertStack/SEO-Workplace#1]
> 19/10/2016, Wednesday
## Session Breakdown:
- From this slide: https://goo.gl/JqF4LI
## Resource:
- https://www.google.com/intl/kn/insidesearch/howsearchworks/thestory/
## Task:
- [ ] Class Review / Feedback: 5(five) Main Ideas about previous class via [Google form](https://goo.gl/forms/08xGcK4i5KOVmTEg1).
- [ ] Social Media Profile creation: https://www.linkedin.com
- [ ] Provide Example @ Learning Stage of 'Google Search Hack'

**Comment by MrMehedi** [comment]
MY linkedin profile link: https://bd.linkedin.com/in/mehedi-diu

**Comment by Fhd34** [comment]
https://www.linkedin.com/in/mohammad-al-fahad-996968130?trk=nav_responsive_tab_profile_pic

**Comment by SufiAhmedHamim** [comment]
**My linkedin profile link**: https://www.linkedin.com/in/sufiahmed

**Comment by AmirHossainRhidoy** [comment]
Linkedin Profile link: https://www.linkedin.com/in/amirhossainrhidoy

**Comment by sakiftaswar1** [comment]
My linkedin profile link :
https://www.linkedin.com/in/sakif-taswar

**Comment by mofidulislamporag** [comment]
https://www.linkedin.com/in/mofidul-islam-porag-805b2a130?trk=nav_responsive_tab_profile

**Comment by Fhd34** [comment]
https://www.linkedin.com/in/mohammad-fahad36

**Comment by Fhd34** [comment]
Attend chilam Na Class ta te tai review dite parchi na sorry

**Comment by Md-Rakibul** [comment]
https://www.linkedin.com/in/rakibul-islam-rasel-339758130?trk=hp-identity-name

**Comment by AR-Aminur** [comment]
https://www.linkedin.com/in/akr-aminur-072028131

**Comment by hossainarif** [comment]
https://www.linkedin.com/in/arif-hossain-joy-472b33130?trk=nav_responsive_tab_profile

**Comment by pronob980** [comment]
https://www.linkedin.com/in/pronob-roy-203766130?trk=nav_responsive_tab_profile

**Comment by SarwarMilon** [comment]
https://www.linkedin.com/in/sarwar-mahmud-milon-3b7b38130?trk=nav_responsive_tab_profile

**Comment by a1amin** [comment]
https://bd.linkedin.com/in/md-al-amin-khan-722777126

**Comment by MasodurRahmanShanto** [comment]
https://www.linkedin.com/in/masodur-rahman-shanto-a7a79a126?trk=nav_responsive_tab_profile
https://medium.com/@masodurrahmanshanto

**Comment by mahdi-jewel** [comment]
linkedin ID
https://www.linkedin.com/in/mahdi-jewel-928885124?trk=nav_responsive_tab_profile
