### ISSUE TITLE
SEO Basics - Module II

### ISSUE THREAD

**Issue by NaSabbir** [XpertStack/SEO-Workplace#3]
> 26/10/2016, Wednesday
# Wide Web Space Concept
## Session Breakdown:
- [x] Engaged Previous Tasking
- [x] Define :: Domain Name
- [x] Web Hosting
- [x] Wordpress.com VS WordPress.org
- [x] Learn About Wordpress Dashboard

:octocat: ‼️ URL and Domain are same?
## Resource:
1. https://www.google.com.bd/trends/
2. To learn simple web technologies
## Task:
- [ ] Class Review / Feedback: 5(five) Main Ideas about previous class via [Google form](https://goo.gl/forms/08xGcK4i5KOVmTEg1).
- [ ] :grey_question:  Quiz : Preparation :paperclip: 
- [ ] Account Creation: https://wordpress.com + https://medium.com  +  https://www.quora.com
- [ ] Write Google bomb while your research

**Comment by MehediDiu** [comment]
http://stackoverflow.com/users/7073878/mahfujur-rahman-mehedi

http://seoforums.org/profile/activity

https://www.reddit.com/user/Mehedi_Diu/

**Comment by sadiqur9670** [comment]
https://wordpress.com/me
https://medium.com/@srrifat9670
https://www.quora.com/profile/Sadiqur-Rahman-Rifat

About Google bomb:
Google bomb is a terms that any web site come to the top position at search engine result list. Like as SEO. It done by according to Google search-rank algorithm. 
"Adam Mathes" first use this word"Google bomb" at 6 April 2001.
It mainly use business, political, or comedic.

**Comment by AR-Aminur** [comment]
https://wordpress.com/me
https://medium.com/@akraminur
https://www.quora.com/profile/Akr-Aminur

**Comment by pronob980** [comment]
https://wordpress.com/me
https://medium.com/@pronobkumarroy
https://www.quora.com/profile/Pronob-Kumar-Roy

**Comment by arif98741** [comment]
Wordpress
https://en.gravatar.com/arif98741

**Comment by arif98741** [comment]
Wordpress
https://en.gravatar.com/arif98741
https://medium.com/@arif98741
https://www.quora.com/profile/Ariful-Islam-209

**Comment by Md-Shahidul** [comment]
http://shahidulweb.wordpress.com
https://www.quora.com/profile/Md-Shahidul-Islam-Khukon-1
https://medium.com/@shahidul.cse.diu

**Comment by NaSabbir** [comment]
Task as:
- https://imsabbir.wordpress.com
- https://medium.com/@NaSabbir
- https://www.quora.com/profile/Nazir-Ahmed-Sabbir

**Comment by SufiAhmedHamim** [comment]
- https://medium.com/@sufiahmed
- https://www.quora.com/profile/Sufi-Ahmed-Hamim
- http://sufiahmedblog.wordpress.com/

**Comment by MrMehedi** [comment]
https://medium.com/@mehedidiu1020
https://www.quora.com/profile/Mehedi-7
http://mehedipro.wordpress.com

**Comment by AmirHossainRhidoy** [comment]
1: Wordpress: http://amirhossainme.wordpress.com/ 
2: Medium: https://medium.com/@amirhossain
3: Quora: https://www.quora.com/profile/Md-Amir-Hossain-Rhidoy

**Comment by SarwarMilon** [comment]
https://gravatar.com/sarwarcom

**Comment by mofidulislamporag** [comment]
https://medium.com/@mofidulislamporag
https://www.quora.com/profile/Mofidulislamporag
https://mofidulislamporag.wordpress.com/

**Comment by SarwarMilon** [comment]
https://en.gravatar.com/sarwarcom

**Comment by SarwarMilon** [comment]
https://wordpress.com/stats/insights/sarwarcom.wordpress.com

**Comment by SarwarMilon** [comment]
https://www.quora.com/profile/Sarwar-Mahmud-Milon

**Comment by SarwarMilon** [comment]
https://medium.com/@sarwarmahmudmilon

**Comment by SarwarMilon** [comment]
https://wordpress.com/stats/insights/sarwarcom.wordpress.com
https://medium.com/@sarwarmahmudmilon
https://www.quora.com/profile/Sarwar-Mahmud-Milon

**Comment by sakiftaswar1** [comment]
https://www.quora.com/profile/Sakif-Taswar
https://medium.com/@sakiftaswar1
https://secure.gravatar.com/sakiftaswar1

**Comment by a1amin** [comment]
https://www.quora.com/profile/MD-Al-Amin-Khan-1
https://medium.com/@mdalaminkhan
http://alaminkhaan.wordpress.com

**Comment by Fhd34** [comment]
https://fhd36.wordpress.com

**Comment by Fhd34** [comment]
https://medium.com/@alfahad42044

**Comment by Fhd34** [comment]
https://www.quora.com/profile/Al-Fahad-9

**Comment by hossainarif** [comment]
https://medium.com/@arifhossainjoyh

**Comment by hossainarif** [comment]
https://wordpress.com/me

**Comment by hossainarif** [comment]
https://www.quora.com/profile/Arif-Hossain-162-15-1095

**Comment by MasodurRahmanShanto** [comment]
https://masodur.wordpress.com/

**Comment by Md-Rakibul** [comment]
https://wordpress.com/stats/insights/5787blog.wordpress.com
https://medium.com/@rakibba5787
https://www.quora.com/profile/MD-Rakibul-Islam-25

**Comment by Ariful1073diu** [comment]
https://medium.com/@ARIFUL9

**Comment by Ariful1073diu** [comment]
https://ariful3c.wordpress.com/

**Comment by Ariful1073diu** [comment]
https://www.quora.com/profile/Md-Ariful-Islam-162-15-1073
