### ISSUE TITLE
Keyword Research Basics

### ISSUE THREAD

**Issue by NaSabbir** [XpertStack/SEO-Workplace#4]
> 30/10/2016, Sunday
## Session Breakdown:
- Introduction to Keyword Research
- Tools in the market
- Importance of KW Research
- To understand competition
- 

## Resource:
- https://adwords.google.com/KeywordPlanner
- http://www.wordstream.com/keywords
- http://www.keywordeye.com
- http://www.keyworddiscovery.com
- 

## Task:
- [ ] Class Review / Feedback: 5(five) Main Ideas about previous class via [Google form](https://goo.gl/forms/08xGcK4i5KOVmTEg1).

- [ ] Finding KW up to 20
- [ ] Show up your Search result

**Comment by Md-Shahidul** [comment]
[New Text Document.txt](https://github.com/XpertStack/SEO-Workplace/files/573760/New.Text.Document.txt)

**Comment by arif98741** [comment]
[Keyword Research.docx](https://github.com/XpertStack/SEO-Workplace/files/573768/Keyword.Research.docx)

**Comment by MasodurRahmanShanto** [comment]
NISS-Cricket

1.BPL cricket tournament
2.worldcup cricket
3.best cricket player in the world
4.top 10 bowler in cricket
5.best bd player
6.how i can play cricket
7.cricket instrument
8.top expensive cricketer in BPL
9.IPL best cricketer 
10.BPL best bowler
11.highest score in cricket history
12.top 10 batsman in cricket
13.popular tournament in cricket
14.who is best bowler in cricket
15.most century in 1 cricket match
16.most famous cricketer in bd
17.cricket rules
18.cricket umpiring rules
19.live cricket score
20.live cricket match

**Comment by sadiqur9670** [comment]
Nish: C programming language
Keyword:
1.  What is c programming language?
2.  How to learn c programming language.
3.  Define: c programming language.
4.  Defecation of c programing language.
5.   About c programming language.
6.  How to write c language.
7.  Code blocks
8.  Code chef
9.  Android c programming language.
10.What is c compiler.
11.C compilers
12.code academy
13.codemarshal
14.uri online judge.
15.online compiler.
16. Basic programming language.

**Comment by md-labib** [comment]
1-Cycles

2-buy cycle

3-new buy cycle

4-old buy  cycle

5-new 2016 cycle

5-new 1992-2000 buy cycle

6-new 2016 buy cycle

7-black buy cycle

8-top 10 buy cycle

9-raceing buy cycle

10-raceing new buy cycle

11-new 2016 raceing buy cycle

12-new cycle price 

13-new cycle price in bd

14-cycle online price

15-soprts buy cycle

16-soprts new buy cycle

17-2016 new sports buy cycle

18-new brand sports buy cycle

19-top 10 brand buy cycle

20-best bye cycle in the world
