### ISSUE TITLE
Boosting On-Page

### ISSUE THREAD

**Issue by NaSabbir** [XpertStack/SEO-Workplace#8]
> 06/12/2016, Tuesday

## Session Breakdown:

- Scratch from Basic!
- Pre-Quiz :: Experience, Reputation , Connections
- SEO Strategy - **Bounce rate**

### [On-page SEO](https://moz.com/blog/category/on-page-seo) :

- [ ] [Infograph](https://d2vepvd49xw1a6.cloudfront.net/wp-content/uploads/2016/05/19115419/on_page_seo_infographic_v3-1.png)
- [ ] URL/Permalink Strings
- [ ] **Title** - How Modified your [Title Tag](https://moz.com/learn/seo/title-tag)?
--- Heading - Sub Heading
- [ ] Meta Description - Idea of your Blog
- [ ] Meta Tag
![image065](https://cloud.githubusercontent.com/assets/11223477/20914701/9705b4a0-bbab-11e6-8aec-2ee72d015ce2.jpg)

- [ ] Image Optimization
- [ ] Outbound Links
- [ ] Internal Links
--- Anchor Text ---
- [ ] Quality Content - King () Queen !
--- Keyword Targeted Content, LSI, LTK ---
- [ ] [Mobile Responsive](https://search.google.com/search-console/mobile-friendly)
- [ ] Blog Comments
- [ ] [Page Speed](https://webmasters.googleblog.com/2011/03/introducing-page-speed-online-with.html) 
- [ ] Google Algorithm
- [ ] 

## Resource:

- http://www.stephanspencer.com/matt-cutts-interview/
- 
- http://www.teamseohero.com/ 

## Task:
- [ ] Class Review / Feedback: 5(five) Main Ideas about previous class via [Google form](https://goo.gl/forms/08xGcK4i5KOVmTEg1).

- [ ]
